### ISSUE TITLE
upgrade to version 2.11.5

### ISSUE THREAD

**Issue by keetron** [fhoeben/hsac-fitnesse-plugin#19]
After updating the pom file to use the newest release, we ran into issues when running the tests where the range parameters are not recognized.
It was resolved after we removed the old versions of the plugin from the plugins folder.
Thought you might wanted to know.

**Comment by fhoeben** [comment]
I'm glad you found what the problem was, and how to address it.

I anticipated this might be a problem in general. That's why the general upgrade instructions in the sample project (https://github.com/fhoeben/sample-fitnesse-project#upgrading) explicitly have a command `mvn clean -Pdelete-hsac-fitnesse-fixture` that (amongst other things) deletes old plugin versions. 
I don't like having to repeat this in each release, but it should be clear. Any suggestion how this can be easier, or more prominent/clear, so that people upgrading know what to do (if they have to do anything at all)?

**Comment by keetron** [comment]
A simple line saying: "When upgrading from an older version, delete the plugins folder to remove old versions of the packaged plugins" somewhere in the top block on https://github.com/fhoeben/hsac-fitnesse-fixtures/releases would work, I think?

**Comment by fhoeben** [comment]
Updated https://github.com/fhoeben/hsac-fitnesse-fixtures/releases/tag/2.11.5
