### ISSUE TITLE
Table template: how to comment out some lines

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-plugin#44]
Is there a way to comment out some lines of a table template calling table; i.e. of the second table shown below ?

Taken from
https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-fixtures/master/wiki/FitNesseRoot/HsacExamples/SlimTests/BrowserTests/TableTemplateTest.wiki
```
|table template|album details                                |
|scroll to     |@{album}                                     |
|$year=        |value of|Year |in row where|Album|is|@{album}|
|$label=       |value of|Label|in row where|Album|is|@{album}|


|album details                          |
|album       |year?|label?              |
|Astral Weeks|1968 |Warner Bros.        |
|Moondance   |1970 |Rhino / Warner Bros.|
```

I want to be able to see all lines that I ever ran, but comment all of the lines out, except the one that I ran most recently.
I currently have multiple tables, each with one album/year/label line, and all but one of those tables are prefixed with a |Comment| line.

```
|Comment|
|album details                          |
|album       |year?|label?              |
|Astral Weeks|1968 |Warner Bros.        |

|album details                          |
|album       |year?|label?              |
|Moondance   |1970 |Rhino / Warner Bros.|
```

Note: the example makes more sense with 10 or more albums shown. Then the code duplication really is in your face.

Note: I once saw a workaround, where an extra parameter was passed to the table template, and that parameter was in the first cell of each command within the table template; if the parameter was '#'  , then the command wasn't executed; but I can't figure out how to get this to work if the commands within the table template, actually include a "start" line to set a new actor, and a "show" line, where "show" is built-in into the script table.

**Comment by fhoeben** [comment]
I don't know an approach of the top of my head, but given your description I do have some ideas.

I assume you normally want to execute all tables, but for some debugging purposes you want to focus on the last. Or you want to show everything ever done and a 'current' row. 

My idea would be to have just two tables: one big one (that is commented out if the rows should not be executed) and another one with the rows that should be executed. For debugging: just copy lines from the big to the small table (and ensure to uncomment the big table before committing). For historical overview: just add a line to the 2nd table and once it is 'done' move it to the big table.

Why do you have separate tables for each row?

If you really want to toggle each individual row I suppose you can do it with an extra 'table template' indirection. The decision table contains an extra column (run: yes/no) and the 1st level table template uses that value to determine whether to call a table template that actually does anything, or one that performs no action. I haven't tested this, but I believe one can use a variable in row to change what table template is executed. Something like [this sample page](https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-plugin/master/src/test/wiki/FitNesseRoot/HsacPlugin/NestedTableTemplateTest.wiki) and then use a variable in `T2` to either call `T1_yes` or `T1_no` (where one performs the actions and one does not.

**Comment by fhoeben** [comment]
(I was thinking the big table always remains unchanged, so it would only be a matter of copying a line from the big table and pasting it to the small.)

Anyway I think all three ways could achieve what you are looking for. I think it's a matter of taste which you prefer.

You could check whether you actually need to repeat the parameters in your 'option 2' table, the table template might be smart enough to figure those out based on the definition of `album details` (I'm not 100% sure since the name of table template call now has a `@{prefix}` in front of it). 

Also a`|$description=|has value|Year: @{year}, Album: @{album}, Label: @{label}|` in your `album details` in option 2 might be sufficient to be able to use the output parameter (again having the `@{prefix}` makes me unsure).

Anyway all 3 approaches would work, but personally I feel the simplicity of having a big 'comment table' and a small 'run table' is still a better option.
