### ISSUE TITLE
ENH: Table template, continue on exception

### ISSUE THREAD

**Issue by teunisv** [fhoeben/hsac-fitnesse-plugin#45]
Currently once exception occurs the test stops.
Especially in case of table templates it would be nice it would atleast try to do next line
(yeah I realize that odds are that next ones will fail too, but would atleast nice to try)

side note for the project in question I use a lot of nested table templates, and would be nice if it continues with the top table template and not the next (nested) template 

in this example first line would create exception in 1,2,3 line and would great if it executed 4,5,6 anyway
```
|table template|T1   |
|echo          |@{P3}|
|echo          |@{P1}|
#exeption if P1 == 1

|table template|T2   |
|T1                  |
|echo          |@{P2}|

|script|echo fixture|

|T2      |
|P1|P2|P3|
|1 |2 |3 |
|4 |5 |6 |
```

**Comment by fhoeben** [comment]
Especially with the (understandable) desire to continue with the next top-level row I don't really see how this could be implemented.

I believe the fact that the test is stopped on exception really depends on the exception being thrown. I assume in your case the exception is probably a '...StopTestException'. 

Given this problem description I believe a workaround seems your best way forward: convert the single page with a table template (the one where you would like the test to continue with the next row) into a suite where instead of rows of the table template you have separate test pages. I believe this would immediately give you the behaviour you are looking for (and makes it possible to do a re-run of only the failed tests (formerly rows) to get quick feedback after changes or to check whether tests are flaky.

Writing and maintaining the separate pages could be bit more cumbersome, and the overview of having all test cases in a single table is of course very nice. You could actually keep such an overview page and use it to generate the test pages in the suite I described above. I believe [my fixture project](https://github.com/fhoeben/hsac-fitnesse-fixtures) already contains an example of such an approach. See the [GeneratedSymbolicLinkSuite](https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-fixtures/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite.wiki) in its examples, the full details are at https://github.com/fhoeben/hsac-fitnesse-fixtures/tree/master/wiki/FitNesseRoot/HsacExamples/SlimTests/UtilityFixtures/GeneratedSymbolicLinkSuite

Maybe this approach could be done using a special table type but that seems like quite an effort requiring changes in FitNesse itself. I don't think a plugin can do this at the moment. But feel free to submit a PR if you see a way.
