### ISSUE TITLE
screenshot files are written to the wrong directory

### ISSUE THREAD

**Issue by violinner2** [fhoeben/hsac-fitnesse-plugin#6]
I am using the hsac-fitnesse-plugin for taking screenshots of web services, running tests for many projects through Jenkins, often simultaneously.  The configuration has two directory hierarchies: one with the common Fitnesse installation and plug-ins, and another hierarchy containing the work to test, invoked as:

java -cp "fitnesse-standalone.jar;."  -jar ./fitnesse-standalone.jar -d /my/project/path/ -p ${unique_port}

When screenshots are taken, the screen shot file is saved under the ./FitnesseRoot/files/screenshot/ hierarchy, and the link to the screenshot file is broken in the Fitnesse wiki.  Changing the screenshot name to begin with a "/" does not change this.

Is there a configuration or change which I can make to save the screen shot files below the "-d path" and make the image file display correctly in the test results of the project's Finesse Wiki?

# ideal solution:
|wait for visible|The result is:|
|show  |take screenshot|${project_root}/result_5|

Thanks,
Joel DeWitt

**Comment by fhoeben** [comment]
At the moment there is no option to achieve this. The problem is that the screenshots are made in the process that is started to run the Slim tests, which is actually a different process than the main FitNesse process. FitNesse does not pass the root-path (which you configure using the -d option) to the Slim process, so the information simply is not available to my fixtures to configure the directory to save the screenshots in.
An attempt was made to address this problem in one of the last FitNesse releases. But this fix only made the root path accessible to plugin code, and not yet to fixtures.

On a different note: What I would recommend is running tests from Jenkins as jUnit tests (instead of launching a Java process containing the wiki yourself). This would simplify the configuration of your jobs in Jenkins as you no longer need to configure unique ports, and it also automatically makes Jenkins track the number of tests executed and success/failures. 
That approach also ensures all screenshots are stored in the target/fitnesse-results directory, and are linked properly in the HTML reports generated there.

But this does not allow (for now) for a custom root to be specified. You would need to either: create a 
single hierarchy containing all test pages (i.e. move all current separate hierarchies under a single root), or copy the standard fitnesse jar, plugins and fixtures into multiple projects (one fore each test hierarchy).

I usually employ one of these strategies when maintaining multiple tests sets. Whether I use one or the other depends on whether separate teams are maintaining the test sets or whether the test sets (and their applications to test) evolve independently.

**Comment by violinner** [comment]
I have combined testing into a single hierarchy, and will automate copying of required resources.

One system under test pops up a JavaScript alert dialog, i.e., "Are you sure?"

I hoped to handle this with a script, but the error below results ("Unsupported Command...through... handlesAlerts=false") .  Is there a combination of versions of HSAC, Selenium, PhantomJs (,GhostDriver?), FitNesse, that will allow a headless click-through or silent pass-through of JS alerts in a FitNesse script on CentOS?  Or should the script work, but the command is misspelled?

Thank you in advance for any advice.

>>> Script fragment:
|click | Click Here |
|show | take screenshot | It_is_running |
|confirm alert |

>>> Error: org.openqa.selenium.UnsupportedCommandException: Invalid Command Method ...
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{platform=LINUX, ..., javascriptEnabled=true, browserName=phantomjs, ..., driverVersion=1.2.0, ..., version=2.1.1, ..., handlesAlerts=false

**Comment by fhoeben** [comment]
As far as I'm aware there is no feature in PhantomJs to deal with alerts (see also issue #32).
My recommendation (as always is): run your tests with a real browser. 
Yes, sometimes headless testing can have its place, but it's just not as good as real browser testing (your customers also use a different browser than PhantomJs, and Chrome is just quicker).

**Comment by violinner** [comment]
Thank you for your help and patience.

**Comment by violinner** [comment]
Understanding that there is nothing like a real browser, headless testing is nevertheless mandatory.
Is there a way to build or configure HSAC to send the following JavaScript code to the web driver on each new open URL?
("window.confirm = function(){return true;}");

**Comment by fhoeben** [comment]
Yes there is. Create a subclass that overrides `open()` to something like:

```
   @Override
    public boolean open(String address) {
        boolean open = super.open(address);
        if (open) {
            getSeleniumHelper().executeJavascript("window.confirm = function(){return true;}");
        }
        return open;
    }
```

Would that work?
