### ISSUE TITLE
Time stamp is needed for progress through a Browser Test

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-plugin#8]
Is there a convenient way to log the time at which each command of a Browser Test table is executed?
This would be very useful in diagnosing an intermittently slow web site response.

**Comment by fhoeben** [comment]
There is no really simple way to do it for each command. But I see some options:

- You can use [TimerFixture](http://fhoeben.github.io/hsac-fitnesse-fixtures/examples-results/HsacExamples.SlimTests.UtilityFixtures.TimerFixture.html) (maybe as a library) to explicitly track time between two rows, or just show the current time, in a script also using BrowserTest. 
- Or you could subclass BrowserTest and override `takeScreenshot()` to output the current time (or elapsed time), instead of an actual screenshot, and the use a 'storyboard' table.
- Or you could subclass BrowserTest and override `afterCompletion()`, or `aroundSlimInvoke()`, to output the current (or elapsed) time after each call to BrowserTest to system out or a file.

I believe @DV3D has something that works along the lines of the 3rd option, but I don't know the current status of that.

Does this help?

**Comment by violinner** [comment]
Extending BrowserTest sounds like my best option.
Thanks!
